package com.yaowk.device.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGoods<M extends BaseGoods<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setDeviceId(java.lang.Integer deviceId) {
		set("device_id", deviceId);
		return (M)this;
	}

	public java.lang.Integer getDeviceId() {
		return get("device_id");
	}

	public M setStock(java.lang.Integer stock) {
		set("stock", stock);
		return (M)this;
	}

	public java.lang.Integer getStock() {
		return get("stock");
	}

	public M setCritical(java.lang.Integer critical) {
		set("critical", critical);
		return (M)this;
	}

	public java.lang.Integer getCritical() {
		return get("critical");
	}

	public M setStatus(java.lang.String status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.String getStatus() {
		return get("status");
	}

}
