package com.yaowk.device.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseReplenishmentLog<M extends BaseReplenishmentLog<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setDeviceId(java.lang.Integer deviceId) {
		set("device_id", deviceId);
		return (M)this;
	}

	public java.lang.Integer getDeviceId() {
		return get("device_id");
	}

	public M setNumber(java.lang.Integer number) {
		set("number", number);
		return (M)this;
	}

	public java.lang.Integer getNumber() {
		return get("number");
	}

	public M setRemainder(java.lang.Integer remainder) {
		set("remainder", remainder);
		return (M)this;
	}

	public java.lang.Integer getRemainder() {
		return get("remainder");
	}

	public M setGoodsId(java.lang.Integer goodsId) {
		set("goods_id", goodsId);
		return (M)this;
	}

	public java.lang.Integer getGoodsId() {
		return get("goods_id");
	}

	public M setReplenishmentId(java.lang.Integer replenishmentId) {
		set("replenishment_id", replenishmentId);
		return (M)this;
	}

	public java.lang.Integer getReplenishmentId() {
		return get("replenishment_id");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
