package com.yaowk.user.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("sys_fans", "id", Fans.class);
		arp.addMapping("sys_menu", "id", Menu.class);
		arp.addMapping("sys_role", "id", Role.class);
		arp.addMapping("sys_role_menu", "id", RoleMenu.class);
		arp.addMapping("sys_user", "id", User.class);
		arp.addMapping("sys_user_role", "id", UserRole.class);
	}
}

