package com.yaowk.user.model;

import com.yaowk.common.plugin.FindKv;
import com.jfinal.plugin.activerecord.SqlPara;
import java.util.List;
import com.yaowk.user.model.base.BaseFans;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Fans extends BaseFans<Fans> {
	public static final Fans dao = new Fans().dao();
	protected static final String tableNamePrefix = "sys_";

	public static String tableName(String table) {
		return tableNamePrefix + table;
		}

	public List<Fans> find(FindKv kv) {
		SqlPara sqlPara = getSqlPara("find", kv);
		return find(sqlPara);
}

}
