package com.yaowk.user.model;

import com.jfinal.json.Json;
import com.jfinal.plugin.activerecord.SqlPara;
import com.yaowk.common.constant.CacheConstant;
import com.yaowk.common.kit.DbCacheKit;
import com.yaowk.common.plugin.FindKv;
import com.yaowk.user.model.base.BaseFans;

import java.util.List;
import java.util.Map;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Fans extends BaseFans<Fans> {
    public static final Fans dao = new Fans().dao();
    protected static final String tableName = "sys_fans";

    public List<Fans> find(Map condition) {
        FindKv kv = FindKv.create().setCondition(condition).setTable(tableName);
        SqlPara sqlPara = getSqlPara("find", kv);
        String key = "Fans:find:" + Json.getJson().toJson(kv);
        DbCacheKit.addKey(key);
        return findByCache(CacheConstant.DB, key, sqlPara.getSql(), sqlPara.getPara());
    }

}
