package com.yaowk.user.model;

import com.jfinal.plugin.activerecord.SqlPara;
import com.yaowk.common.kit.DbCacheKit;
import com.yaowk.common.plugin.FindKv;
import com.yaowk.user.model.base.BaseRoleMenu;

import java.util.List;
import java.util.Map;

;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleMenu extends BaseRoleMenu<RoleMenu> {
    public static final RoleMenu dao = new RoleMenu().dao();
    protected static final String tableName = "sys_role_menu";

    public List<RoleMenu> find(Map condition) {
        FindKv kv = FindKv.create().setCondition(condition).setTable(tableName);
        SqlPara sqlPara = getSqlPara("find", kv);
        return find(sqlPara);
    }

    @Override
    public boolean save() {
        DbCacheKit.removeCache("user:menu:findByRoleId:" + getRoleId());
        return super.save();
    }

    @Override
    public boolean delete() {
        DbCacheKit.removeCache("user:menu:findByRoleId:" + getRoleId());
        return super.delete();
    }
}
