package com.yaowk.user.model;

import com.jfinal.kit.Kv;
import com.jfinal.plugin.activerecord.SqlPara;
import com.xiaoleilu.hutool.util.CollectionUtil;
import com.yaowk.common.constant.CacheConstant;
import com.yaowk.common.kit.DbCacheKit;
import com.yaowk.common.plugin.FindKv;
import com.yaowk.user.model.base.BaseRole;

import java.util.List;
import java.util.Map;

;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Role extends BaseRole<Role> {
    public static final Role dao = new Role().dao();
    protected static final String tableName = "sys_role";

    public List<Role> find(Map condition) {
        FindKv kv = FindKv.create().setCondition(condition).setTable(tableName);
        SqlPara sqlPara = getSqlPara("find", kv);
        return find(sqlPara);
    }

    public List<Role> findByUserId(Integer userId) {
        SqlPara sqlPara = getSqlPara("role.findByUserId", userId);
        String key = "user:role:findByUserId" + userId;
        DbCacheKit.addKey(key);
        return findByCache(CacheConstant.DB, key, sqlPara.getSql(), sqlPara.getPara());
    }

    @Override
    public boolean update() {
        DbCacheKit.removeCacheStarWith("user:role");
        return super.update();
    }

    @Override
    public boolean delete() {
        Integer roleId = getId();
        Kv condition = Kv.by("role_id = ", roleId);
        // 删除用户角色关系
        List<UserRole> userRoles = UserRole.dao.find(condition);
        if (CollectionUtil.isNotEmpty(userRoles)) {
            for (UserRole userRole : userRoles) {
                userRole.delete();
            }
        }

        // 删除角色按钮关系
        List<RoleMenu> roleMenus = RoleMenu.dao.find(condition);
        if (CollectionUtil.isNotEmpty(roleMenus)) {
            for (RoleMenu roleMenu : roleMenus) {
                roleMenu.delete();
            }
        }
        DbCacheKit.removeCacheStarWith("user:role");
        return super.delete();
    }
}
