package com.yaowk.user.model;

import com.jfinal.plugin.activerecord.SqlPara;
import com.jfinal.json.Json;
import com.yaowk.common.plugin.FindKv;
import com.yaowk.common.constant.CacheConstant;
import com.yaowk.common.kit.DbCacheKit;
import com.yaowk.common.model.base.Page;
import java.util.List;
import java.util.Map;
import com.yaowk.user.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User().dao();
	protected static final String tableName = "t_user";

	public List<User> find(Map condition) {
		FindKv kv = FindKv.create().setCondition(condition).setTable(tableName);
		SqlPara sqlPara = getSqlPara("find", kv);
		String key = "User:find:" + Json.getJson().toJson(kv);
		DbCacheKit.addKey(key);
		return findByCache(CacheConstant.DB, key, sqlPara.getSql(), sqlPara.getPara());
	}

	public com.jfinal.plugin.activerecord.Page<User> paginate(Page page, Map condition) {
		FindKv kv = FindKv.create().setCondition(condition).setTable(tableName);
		SqlPara sqlPara = getSqlPara("paginate-except", kv);
		Json json = Json.getJson();
		String key = "User:paginate:" + json.toJson(page) + json.toJson(kv);
		DbCacheKit.addKey(key);
		return paginateByCache(CacheConstant.DB, key, page.getPageNumber(), page.getPageSize(), getSql("paginate-select"), sqlPara.getSql(), sqlPara.getPara());
	}

	@Override
	public boolean save() {
		DbCacheKit.removeCacheStarWith("User:paginate");
		return super.save();
	}

	@Override
	public boolean update() {
		DbCacheKit.removeCacheStarWith("User");
		return super.update();
	}

	@Override
	public boolean delete() {
		DbCacheKit.removeCacheStarWith("User");
		return super.delete();
	}

}
