package com.yaowk.user.model;

import com.jfinal.plugin.activerecord.SqlPara;
import com.yaowk.common.kit.DbCacheKit;
import com.yaowk.common.plugin.FindKv;
import com.yaowk.user.model.base.BaseUserRole;

import java.util.List;
import java.util.Map;

;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserRole extends BaseUserRole<UserRole> {
    public static final UserRole dao = new UserRole().dao();
    protected static final String tableName = "sys_user_role";

    public List<UserRole> find(Map condition) {
        FindKv kv = FindKv.create().setCondition(condition).setTable(tableName);
        SqlPara sqlPara = getSqlPara("find", kv);
        return find(sqlPara);
    }

    @Override
    public boolean save() {
        DbCacheKit.removeCache("user:role:findByUserId" + getUserId());
        return super.save();
    }

    @Override
    public boolean delete() {
        DbCacheKit.removeCache("user:role:findByUserId" + getUserId());
        return super.delete();
    }
}
