package com.yaowk.user.model;

import com.jfinal.json.Json;
import com.jfinal.kit.Kv;
import com.jfinal.plugin.activerecord.SqlPara;
import com.yaowk.common.constant.CacheConstant;
import com.yaowk.common.kit.DbCacheKit;
import com.yaowk.common.plugin.FindKv;
import com.yaowk.user.model.base.BaseUser;

import java.util.List;
import java.util.Map;

;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
    public static final User dao = new User().dao();
    protected static final String tableName = "sys_user";

    public List<User> find(Map condition) {
        FindKv kv = FindKv.create().setCondition(condition).setTable(tableName);
        SqlPara sqlPara = getSqlPara("find", kv);
        String key = "User:find:" + Json.getJson().toJson(kv);
        DbCacheKit.addKey(key);
        return findByCache(CacheConstant.DB, key, sqlPara.getSql(), sqlPara.getPara());
    }

    public User findByUsername(String username) {
        FindKv findKv = FindKv.create().setTable(tableName);
        Kv condition = Kv.create().set("username = ", username);
        findKv.setCondition(condition);
        SqlPara sqlPara = getSqlPara("find", findKv);
        String key = "User:findByUsername:" + username;
        return findFirstByCache(CacheConstant.DB, key, sqlPara.getSql(), sqlPara.getPara());
    }

}
