package com.yaowk.weixin.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseConfig<M extends BaseConfig<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setPlatformId(java.lang.Integer platformId) {
		set("platform_id", platformId);
		return (M)this;
	}

	public java.lang.Integer getPlatformId() {
		return get("platform_id");
	}

	public M setAppId(java.lang.String appId) {
		set("app_id", appId);
		return (M)this;
	}

	public java.lang.String getAppId() {
		return get("app_id");
	}

	public M setAppSecret(java.lang.String appSecret) {
		set("app_secret", appSecret);
		return (M)this;
	}

	public java.lang.String getAppSecret() {
		return get("app_secret");
	}

	public M setEncodingAesKey(java.lang.String encodingAesKey) {
		set("encoding_aes_key", encodingAesKey);
		return (M)this;
	}

	public java.lang.String getEncodingAesKey() {
		return get("encoding_aes_key");
	}

	public M setMessageEncrypt(java.lang.Integer messageEncrypt) {
		set("message_encrypt", messageEncrypt);
		return (M)this;
	}

	public java.lang.Integer getMessageEncrypt() {
		return get("message_encrypt");
	}

	public M setToken(java.lang.String token) {
		set("token", token);
		return (M)this;
	}

	public java.lang.String getToken() {
		return get("token");
	}

	public M setMchId(java.lang.String mchId) {
		set("mch_id", mchId);
		return (M)this;
	}

	public java.lang.String getMchId() {
		return get("mch_id");
	}

	public M setKey(java.lang.String key) {
		set("key", key);
		return (M)this;
	}

	public java.lang.String getKey() {
		return get("key");
	}

}
