package com.yaowk.weixin.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOrder<M extends BaseOrder<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setPlatformId(java.lang.Integer platformId) {
		set("platform_id", platformId);
		return (M)this;
	}

	public java.lang.Integer getPlatformId() {
		return get("platform_id");
	}

	public M setOutTradeNo(java.lang.String outTradeNo) {
		set("out_trade_no", outTradeNo);
		return (M)this;
	}

	public java.lang.String getOutTradeNo() {
		return get("out_trade_no");
	}

	public M setTotalFee(java.lang.Integer totalFee) {
		set("total_fee", totalFee);
		return (M)this;
	}

	public java.lang.Integer getTotalFee() {
		return get("total_fee");
	}

	public M setSpbillCreateIp(java.lang.String spbillCreateIp) {
		set("spbill_create_ip", spbillCreateIp);
		return (M)this;
	}

	public java.lang.String getSpbillCreateIp() {
		return get("spbill_create_ip");
	}

	public M setTradeType(java.lang.String tradeType) {
		set("trade_type", tradeType);
		return (M)this;
	}

	public java.lang.String getTradeType() {
		return get("trade_type");
	}

	public M setPrepayId(java.lang.String prepayId) {
		set("prepay_id", prepayId);
		return (M)this;
	}

	public java.lang.String getPrepayId() {
		return get("prepay_id");
	}

	public M setCodeUrl(java.lang.String codeUrl) {
		set("code_url", codeUrl);
		return (M)this;
	}

	public java.lang.String getCodeUrl() {
		return get("code_url");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setStatus(java.lang.String status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public M setVersion(java.lang.Integer version) {
		set("version", version);
		return (M)this;
	}

	public java.lang.Integer getVersion() {
		return get("version");
	}

	public M setDeviceId(java.lang.Integer deviceId) {
		set("device_id", deviceId);
		return (M)this;
	}

	public java.lang.Integer getDeviceId() {
		return get("device_id");
	}

	public M setGoodsId(java.lang.Integer goodsId) {
		set("goods_id", goodsId);
		return (M)this;
	}

	public java.lang.Integer getGoodsId() {
		return get("goods_id");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

}
