package com.yaowk.weixin.model;

import com.jfinal.json.Json;
import com.jfinal.plugin.activerecord.SqlPara;
import com.yaowk.common.constant.CacheConstant;
import com.yaowk.common.kit.DbCacheKit;
import com.yaowk.common.model.base.Page;
import com.yaowk.common.plugin.FindKv;
import com.yaowk.weixin.model.base.BaseOrder;

import java.util.List;
import java.util.Map;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Order extends BaseOrder<Order> {
    public static final Order dao = new Order().dao();
    protected static final String tableName = "wx_order";

    public List<Order> find(Map condition) {
        FindKv kv = FindKv.create().setCondition(condition).setTable(tableName);
        SqlPara sqlPara = getSqlPara("find", kv);
        String key = "Order:find:" + Json.getJson().toJson(kv);
        DbCacheKit.addKey(key);
        return findByCache(CacheConstant.DB, key, sqlPara.getSql(), sqlPara.getPara());
    }

    public com.jfinal.plugin.activerecord.Page<Order> paginate(Page page, Map condition) {
        FindKv kv = FindKv.create().setCondition(condition).setTable(tableName);
        SqlPara sqlPara = getSqlPara("paginate-except", kv);
        Json json = Json.getJson();
        String key = "Order:paginate:" + json.toJson(page) + json.toJson(kv);
        DbCacheKit.addKey(key);
        return paginateByCache(CacheConstant.DB, key, page.getPageNumber(), page.getPageSize(), getSql("paginate-select"), sqlPara.getSql(), sqlPara.getPara());
    }

    @Override
    public boolean save() {
        DbCacheKit.removeCacheStarWith("Order:paginate");
        return super.save();
    }

    @Override
    public boolean update() {
        DbCacheKit.removeCacheStarWith("Order");
        return super.update();
    }

    @Override
    public boolean delete() {
        DbCacheKit.removeCacheStarWith("Order");
        return super.delete();
    }

    public static final String STATUS_NO_PAY = "1";
    public static final String STATUS_HAS_PAY = "2";
    public static final String STATUS_HAS_OUT = "3";

}
