package com.yaowk.user.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setUsername(java.lang.String username) {
		set("username", username);
		return (M)this;
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public M setTelPhone(java.lang.String telPhone) {
		set("tel_phone", telPhone);
		return (M)this;
	}

	public java.lang.String getTelPhone() {
		return get("tel_phone");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setBalance(java.math.BigDecimal balance) {
		set("balance", balance);
		return (M)this;
	}

	public java.math.BigDecimal getBalance() {
		return get("balance");
	}

	public M setIntegrate(java.lang.Integer integrate) {
		set("integrate", integrate);
		return (M)this;
	}

	public java.lang.Integer getIntegrate() {
		return get("integrate");
	}

	public M setNickName(java.lang.String nickName) {
		set("nick_name", nickName);
		return (M)this;
	}

	public java.lang.String getNickName() {
		return get("nick_name");
	}

}
