package com.yaowk.user.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setFansId(java.lang.Integer fansId) {
		set("fans_id", fansId);
		return (M)this;
	}

	public java.lang.Integer getFansId() {
		return get("fans_id");
	}

	public M setUsername(java.lang.String username) {
		set("username", username);
		return (M)this;
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public M setNickname(java.lang.String nickname) {
		set("nickname", nickname);
		return (M)this;
	}

	public java.lang.String getNickname() {
		return get("nickname");
	}

	public M setGoldCoin(java.math.BigDecimal goldCoin) {
		set("gold_coin", goldCoin);
		return (M)this;
	}

	public java.math.BigDecimal getGoldCoin() {
		return get("gold_coin");
	}

	public M setBalance(java.math.BigDecimal balance) {
		set("balance", balance);
		return (M)this;
	}

	public java.math.BigDecimal getBalance() {
		return get("balance");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setWx(java.lang.String wx) {
		set("wx", wx);
		return (M)this;
	}

	public java.lang.String getWx() {
		return get("wx");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public M setRealName(java.lang.String realName) {
		set("real_name", realName);
		return (M)this;
	}

	public java.lang.String getRealName() {
		return get("real_name");
	}

	public M setBankCard(java.lang.String bankCard) {
		set("bank_card", bankCard);
		return (M)this;
	}

	public java.lang.String getBankCard() {
		return get("bank_card");
	}

	public M setBank(java.lang.String bank) {
		set("bank", bank);
		return (M)this;
	}

	public java.lang.String getBank() {
		return get("bank");
	}

	public M setParent1(java.lang.Long parent1) {
		set("parent1", parent1);
		return (M)this;
	}

	public java.lang.Long getParent1() {
		return get("parent1");
	}

	public M setParent2(java.lang.Integer parent2) {
		set("parent2", parent2);
		return (M)this;
	}

	public java.lang.Integer getParent2() {
		return get("parent2");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

}
