package com.yaowk.device.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("d_device", "id", Device.class);
		arp.addMapping("d_device_user", "id", DeviceUser.class);
		arp.addMapping("d_goods", "id", Goods.class);
		arp.addMapping("d_replenishment_log", "id", ReplenishmentLog.class);
	}
}

