package com.yaowk.device.model;

import com.jfinal.plugin.activerecord.SqlPara;
import com.jfinal.json.Json;
import com.yaowk.common.plugin.FindKv;
import com.yaowk.common.constant.CacheConstant;
import com.yaowk.common.kit.DbCacheKit;
import com.yaowk.common.model.base.Page;
import java.util.List;
import java.util.Map;
import com.yaowk.device.model.base.BaseDeviceUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeviceUser extends BaseDeviceUser<DeviceUser> {
	public static final DeviceUser dao = new DeviceUser().dao();
	protected static final String tableName = "d_device_user";

	public List<DeviceUser> find(Map condition) {
		FindKv kv = FindKv.create().setCondition(condition).setTable(tableName);
		SqlPara sqlPara = getSqlPara("find", kv);
		String key = "DeviceUser:find:" + Json.getJson().toJson(kv);
		DbCacheKit.addKey(key);
		return findByCache(CacheConstant.DB, key, sqlPara.getSql(), sqlPara.getPara());
	}

	public DeviceUser findFirst(Map condition) {
		List<DeviceUser> result = find(condition);
		return result.size() > 0 ? result.get(0) : null;
	}

	public com.jfinal.plugin.activerecord.Page<DeviceUser> paginate(Page page, Map condition) {
		FindKv kv = FindKv.create().setCondition(condition).setTable(tableName);
		SqlPara sqlPara = getSqlPara("paginate-except", kv);
		Json json = Json.getJson();
		String key = "DeviceUser:paginate:" + json.toJson(page) + json.toJson(kv);
		DbCacheKit.addKey(key);
		return paginateByCache(CacheConstant.DB, key, page.getPageNumber(), page.getPageSize(), getSql("paginate-select"), sqlPara.getSql(), sqlPara.getPara());
	}

	@Override
	public boolean save() {
		DbCacheKit.removeCacheStarWith("DeviceUser:paginate");
		return super.save();
	}

	@Override
	public boolean update() {
		DbCacheKit.removeCacheStarWith("DeviceUser");
		return super.update();
	}

	@Override
	public boolean delete() {
		DbCacheKit.removeCacheStarWith("DeviceUser");
		return super.delete();
	}

}
