package com.yaowk.device.model;

import com.jfinal.json.Json;
import com.jfinal.plugin.activerecord.SqlPara;
import com.yaowk.common.constant.CacheConstant;
import com.yaowk.common.kit.DbCacheKit;
import com.yaowk.common.model.base.Page;
import com.yaowk.common.plugin.FindKv;
import com.yaowk.device.model.base.BaseGoods;

import java.util.List;
import java.util.Map;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Goods extends BaseGoods<Goods> {
    public static final Goods dao = new Goods().dao();
    protected static final String tableName = "d_goods";

    public List<Goods> find(Map condition) {
        FindKv kv = FindKv.create().setCondition(condition).setTable(tableName);
        SqlPara sqlPara = getSqlPara("find", kv);
        String key = "Goods:find:" + Json.getJson().toJson(kv);
        DbCacheKit.addKey(key);
        return findByCache(CacheConstant.DB, key, sqlPara.getSql(), sqlPara.getPara());
    }

    public com.jfinal.plugin.activerecord.Page<Goods> paginate(Page page, Map condition) {
        FindKv kv = FindKv.create().setCondition(condition).setTable(tableName);
        SqlPara sqlPara = getSqlPara("paginate-except", kv);
        Json json = Json.getJson();
        String key = "Goods:paginate:" + json.toJson(page) + json.toJson(kv);
        DbCacheKit.addKey(key);
        return paginateByCache(CacheConstant.DB, key, page.getPageNumber(), page.getPageSize(), getSql("paginate-select"), sqlPara.getSql(), sqlPara.getPara());
    }

    @Override
    public boolean save() {
        DbCacheKit.removeCacheStarWith("Goods:paginate");
        return super.save();
    }

    @Override
    public boolean update() {
        DbCacheKit.removeCacheStarWith("Goods");
        return super.update();
    }

    @Override
    public boolean delete() {
        DbCacheKit.removeCacheStarWith("Goods");
        return setStatus(STATUS_DELETE).update();
    }

    public static final String STATUS_UP = "1"; // 上架
    public static final String STATUS_DOWN = "2"; // 下架
    public static final String STATUS_DELETE = "3"; // 删除

}
